In [10]:
import torch
x=torch.arange(12).reshape((3,4))
x



tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [11]:
Y=torch.tensor([[0,4,5,6],[7,8,9,20],[4,3,2,1]])
Y

tensor([[ 0,  4,  5,  6],
        [ 7,  8,  9, 20],
        [ 4,  3,  2,  1]])

In [12]:
torch.cat((x,Y),dim=0)
torch.cat((x,Y),dim=1)

tensor([[ 0,  1,  2,  3,  0,  4,  5,  6],
        [ 4,  5,  6,  7,  7,  8,  9, 20],
        [ 8,  9, 10, 11,  4,  3,  2,  1]])

In [13]:
x==Y

tensor([[ True, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [25]:
x<Y

tensor([[False,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [14]:
x.sum()#对所有元素求和

tensor(66)

In [16]:
a=torch.arange(3).reshape((3,1))
b=torch.arange(2).reshape((1,2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [17]:
a+b
#广播机制 成为3*2的矩阵相加 a 复制列，b复制行


tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [19]:
#切片
x[-1],x[1:3]

(tensor([ 8,  9, 10, 11]),
 tensor([[ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]))

In [20]:
x[1,2]=22
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5, 22,  7],
        [ 8,  9, 10, 11]])

In [23]:
# 节省内存
before=id(Y)
Y=x+Y
id(Y)==before
#为结果分配新的内存

True

In [24]:
before=id(Y)
Y[:]=x+Y
id(Y)==before
#原地更改

True

In [28]:
a=torch.tensor([3.5])
a.item(),float(a), int(a)

<class 'float'>


In [33]:
a=torch.arange(12).reshape(2,3,2)
b=torch.arange(6).reshape(2,3,1)
print(a)
print(b)
print(a+b)
#三维的广播机制也是试用的

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]]])
tensor([[[0],
         [1],
         [2]],

        [[3],
         [4],
         [5]]])
tensor([[[ 0,  1],
         [ 3,  4],
         [ 6,  7]],

        [[ 9, 10],
         [12, 13],
         [15, 16]]])
