In [3]:
import os

os.makedirs(os.path.join('..','data'),exist_ok=True)
#写入数据
data_file=os.path.join('..','data','house_tiny.csv')
with open(data_file,'w') as f:
    input='NumRooms'
    out='Alley'
    z='Price'
    f.write(f'{input},{out},{z},\n')
    f.write('NA,Pave,127500\n')
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')



In [82]:
import pandas as pd
#读入数据
data=pd.read_csv('../data/house_tiny.csv')
data

NumRooms  Alley  Price
0       NaN   Pave    NaN
1       2.0  dhhaj    NaN
2       4.0    NaN    NaN
3       NaN    NaN    NaN
4       NaN    NaN    NaN
5       NaN    NaN    NaN
6       NaN    NaN    NaN
7       NaN    NaN    NaN

In [83]:
input=data.iloc[:,0:2]
print(input)
#注，iloc对索引数字操作，loc对字段操作
output=data.iloc[:,2:3]
print(output)

input=input.fillna(input.mean())
print(input)


   NumRooms  Alley
0       NaN   Pave
1       2.0  dhhaj
2       4.0    NaN
3       NaN    NaN
4       NaN    NaN
5       NaN    NaN
6       NaN    NaN
7       NaN    NaN
   Price
0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
6    NaN
7    NaN
   NumRooms  Alley
0       3.0   Pave
1       2.0  dhhaj
2       4.0    NaN
3       3.0    NaN
4       3.0    NaN
5       3.0    NaN
6       3.0    NaN
7       3.0    NaN


/var/folders/gv/kg_fzj49523g47cvbk6pwmyc0000gn/T/ipykernel_5084/1953307288.py:7: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  input=input.fillna(input.mean())


In [85]:
inputs=pd.get_dummies(input,)
# 是否给空值再加一行
print(inputs)

   NumRooms  Alley_Pave  Alley_dhhaj
0       3.0           1            0
1       2.0           0            1
2       4.0           0            0
3       3.0           0            0
4       3.0           0            0
5       3.0           0            0
6       3.0           0            0
7       3.0           0            0


In [86]:
import torch
x=torch.tensor(inputs.to_numpy(int))
y=torch.tensor(output.to_numpy(float))
x,y

(tensor([[3, 1, 0],
         [2, 0, 1],
         [4, 0, 0],
         [3, 0, 0],
         [3, 0, 0],
         [3, 0, 0],
         [3, 0, 0],
         [3, 0, 0]]),
 tensor([[nan],
         [nan],
         [nan],
         [nan],
         [nan],
         [nan],
         [nan],
         [nan]], dtype=torch.float64))

In [77]:
#work1
import pandas as pd
max_name=0
max_na=0
data=pd.read_csv('../data/house_tiny.csv')
print(data)
df_=data.isna().sum()
print(df_)
print(df_.values)
for name,value in zip(df_.index,df_.values):
    if max_na<value:
        max_na=value
        max_name=name
    else:
        pass
data.drop(columns=max_name,axis=1)

    

    
        
    


   NumRooms Alley  Price
0       NaN  Pave    NaN
1       2.0   NaN    NaN
2       4.0   NaN    NaN
3       NaN   NaN    NaN
4       NaN   NaN    NaN
5       NaN   NaN    NaN
6       NaN   NaN    NaN
7       NaN   NaN    NaN
NumRooms    6
Alley       7
Price       8
dtype: int64
[6 7 8]


NumRooms Alley
0       NaN  Pave
1       2.0   NaN
2       4.0   NaN
3       NaN   NaN
4       NaN   NaN
5       NaN   NaN
6       NaN   NaN
7       NaN   NaN