In [14]:
import numpy as np
np.array([1,2])

array([1, 2])

In [15]:
from mxnet import np,npx

npx.set_np()
x=np.array(3)
x



/Users/wacai/anaconda3/envs/myenv/lib/python3.11/site-packages/mxnet/numpy/utils.py:37: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  bool = onp.bool


AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [ ]:
import torch
x=torch.tensor(3.0)
y=torch.tensor(2.0)
x+y,x*y,x**y

(tensor(5.), tensor(6.), tensor(9.))

In [ ]:
x=torch.arange(4).reshape(2,2,1)
x
#列向量

tensor([[[0],
         [1]],

        [[2],
         [3]]])

In [ ]:
x[0]
#索引访问

tensor([[0],
        [1]])

In [ ]:
x.shape

torch.Size([2, 2, 1])

In [ ]:
x=torch.arange(20).reshape(5,4)
x


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [ ]:
y=x.T
y

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [ ]:
#张量
X=torch.arange(24).reshape(2,3,4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [16]:
A=torch.arange(20).reshape(5,4)

B=A.clone()
A,A+B

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 tensor([[ 0,  2,  4,  6],
         [ 8, 10, 12, 14],
         [16, 18, 20, 22],
         [24, 26, 28, 30],
         [32, 34, 36, 38]]))

In [ ]:
#Hadamard积（Hadamard product
）
A*B

tensor([[  0,   1,   4,   9,  16],
        [ 25,  36,  49,  64,  81],
        [100, 121, 144, 169, 196],
        [225, 256, 289, 324, 361]])

In [ ]:
#张量乘或加一个标量不会改变张量的形状
a=2
x=torch.arange(24,dtype=torch.float32).reshape(2,3,4)
a+x,(a*x).shape

(tensor([[[ 2.,  3.,  4.,  5.],
          [ 6.,  7.,  8.,  9.],
          [10., 11., 12., 13.]],
 
         [[14., 15., 16., 17.],
          [18., 19., 20., 21.],
          [22., 23., 24., 25.]]]),
 torch.Size([2, 3, 4]))

In [ ]:
#降维
A_sum_axis0=A.sum(axis=0)
# A,A_sum_axis0
A_sum_axis1=A.sum(axis=1)
A,A_sum_axis0,A_sum_axis1

(tensor([[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]]),
 tensor([30, 34, 38, 42, 46]),
 tensor([10, 35, 60, 85]))

In [ ]:
x
x_sum_axis=x.sum(axis=2)

x,x_sum_axis
#对行求和降为，只剩下列

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([[ 6, 22, 38],
         [54, 70, 86]]))

In [ ]:
x.sum(axis=[0,1,2])

x.sum()/x.numel(),x.mean()

(tensor(11.5000), tensor(11.5000))

In [ ]:
#计算平均值也可以降为
x.mean(axis=0)
x.mean(axis=1)

tensor([[ 4.,  5.,  6.,  7.],
        [16., 17., 18., 19.]])

In [ ]:
#非降维求和 3个括号
sum_x=x.sum(axis=1,keepdim=True)
sum_x

tensor([[[12., 15., 18., 21.]],

        [[48., 51., 54., 57.]]])

In [ ]:
X,X/sum_x
#广播机制得要维度相同才能操作，如果把keepdim删除，维度不同会报错

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([[[0.0000, 0.0667, 0.1111, 0.1429],
          [0.3333, 0.3333, 0.3333, 0.3333],
          [0.6667, 0.6000, 0.5556, 0.5238]],
 
         [[0.2500, 0.2549, 0.2593, 0.2632],
          [0.3333, 0.3333, 0.3333, 0.3333],
          [0.4167, 0.4118, 0.4074, 0.4035]]]))

In [ ]:
x,x.cumsum(axis=1)
#累计求和

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.]],
 
         [[12., 13., 14., 15.],
          [16., 17., 18., 19.],
          [20., 21., 22., 23.]]]),
 tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  6.,  8., 10.],
          [12., 15., 18., 21.]],
 
         [[12., 13., 14., 15.],
          [28., 30., 32., 34.],
          [48., 51., 54., 57.]]]))

In [ ]:
#点积 xTy
x1=torch.arange(4,dtype=torch.float32)
y1=torch.ones(4,dtype=torch.float32)
x1,y1,torch.dot(x1,y1)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [18]:
#矩阵向量集,把矩阵A看作一列，每个行向量组成的向量
x = torch.arange(4)
A,x,torch.mv(A,x)


(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 tensor([0, 1, 2, 3]),
 tensor([ 14,  38,  62,  86, 110]))

In [17]:
#在上面我们有了点积和=矩阵的向量集，很轻松得到矩阵乘法
B=torch.arange(12).reshape(4,3)
A,B,torch.mm(A,B)

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 tensor([[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]),
 tensor([[ 42,  48,  54],
         [114, 136, 158],
         [186, 224, 262],
         [258, 312, 366],
         [330, 400, 470]]))

In [21]:
A,A.T,A.T.T
#证明转制的专制等于原数



(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 tensor([[ 0,  4,  8, 12, 16],
         [ 1,  5,  9, 13, 17],
         [ 2,  6, 10, 14, 18],
         [ 3,  7, 11, 15, 19]]),
 tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]))

In [38]:
#范数 l2范数平方和开根号，l1范数绝对值之和
u=torch.tensor([3.0,-4.0,5.0])
torch.norm(u)

tensor(7.0711)

In [41]:
torch.abs(u).sum()

tensor(12.)

In [44]:
#矩阵的范数Frobenius范数。，类似于l2范数平方和开根号
torch.ones((4,9)),torch.norm(torch.ones((4,9)))

(tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.]]),
 tensor(6.))

In [47]:
A=torch.arange(20).reshape(5,4)
B=torch.arange(20).reshape(5,4)
A.T+B.T==(A+B).T

tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])

In [50]:
F=torch.arange(25).reshape(5,5)
F+F.T==(F+F.T).T
#对于任意方阵，A+A的转制总是对称的

tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])

In [52]:
C=torch.arange(24).reshape(2,3,4)
C
len(C)# 长度为2

2

In [56]:
D=torch.arange(24).reshape(3,4,2)
len(D)
#长度始终对应第0轴

3

In [70]:
A,A.sum(axis=1),
# A/A.sum(axis=1),#报错，

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 tensor([ 6, 22, 38, 54, 70]))

In [76]:
C,C.sum(axis=0),C.sum(axis=1),C.sum(axis=2)


(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([[12, 14, 16, 18],
         [20, 22, 24, 26],
         [28, 30, 32, 34]]),
 tensor([[12, 15, 18, 21],
         [48, 51, 54, 57]]),
 tensor([[ 6, 22, 38],
         [54, 70, 86]]))

In [3]:
#norm函数提供3个或3个以上的张量 ---都是平方加一起开根号
import torch
D=torch.arange(12,dtype=torch.float32).reshape(3,2,2) 

D,torch.norm(D) ,

(tensor([[[ 0.,  1.],
          [ 2.,  3.]],
 
         [[ 4.,  5.],
          [ 6.,  7.]],
 
         [[ 8.,  9.],
          [10., 11.]]]),
 tensor(22.4944))